Reapply "just formatting tidy-up"
This reverts commit e78edd9a9cfa5da50c853f231086ce79c34cb8f6.

diff --git a/.local/bin/grimshot b/.local/bin/grimshot
--- a/.local/bin/grimshot
+++ b/.local/bin/grimshot
@@ -13,7 +13,7 @@
 ## See `man 1 grimshot` or `grimshot usage` for further details.
 
 getTargetDirectory() {
-  test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" && \
+  test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
     . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
 
   echo "${XDG_SCREENSHOTS_DIR:-${XDG_PICTURES_DIR:-$HOME}}"
@@ -27,26 +27,26 @@ while [ $# -gt 0 ]; do
   key="$1"
 
   case $key in
-    -n|--notify)
-      NOTIFY=yes
-      shift # past argument
-      ;;
-    -c|--cursor)
-      CURSOR=yes
-      shift # past argument
-      ;;
-    -w|--wait)
-      shift
-      WAIT="$1"
-      if echo "$WAIT" | grep "[^0-9]" -q; then
-        echo "invalid value for wait '$WAIT'" >&2
-        exit 3
-      fi
-      shift
-      ;;
-    *)    # unknown option
-      break # done with parsing --flags
-      ;;
+  -n | --notify)
+    NOTIFY=yes
+    shift # past argument
+    ;;
+  -c | --cursor)
+    CURSOR=yes
+    shift # past argument
+    ;;
+  -w | --wait)
+    shift
+    WAIT="$1"
+    if echo "$WAIT" | grep "[^0-9]" -q; then
+      echo "invalid value for wait '$WAIT'" >&2
+      exit 3
+    fi
+    shift
+    ;;
+  *)      # unknown option
+    break # done with parsing --flags
+    ;;
   esac
 done
 
@@ -104,7 +104,7 @@ die() {
 
 check() {
   COMMAND=$1
-  if command -v "$COMMAND" > /dev/null 2>&1; then
+  if command -v "$COMMAND" >/dev/null 2>&1; then
     RESULT="OK"
   else
     RESULT="NOT FOUND"
@@ -125,7 +125,7 @@ takeScreenshot() {
   fi
 }
 
-if [ "$ACTION" = "check" ] ; then
+if [ "$ACTION" = "check" ]; then
   echo "Checking if required tools are installed. If something is missing, install it to your system and make it available in PATH..."
   check grim
   check slurp
@@ -134,33 +134,33 @@ if [ "$ACTION" = "check" ] ; then
   check jq
   check notify-send
   exit
-elif [ "$SUBJECT" = "area" ] ; then
+elif [ "$SUBJECT" = "area" ]; then
   GEOM=$(slurp -d)
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
     exit 1
   fi
   WHAT="Area"
-elif [ "$SUBJECT" = "active" ] ; then
+elif [ "$SUBJECT" = "active" ]; then
   FOCUSED=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?, .floating_nodes[]?) | select(.focused)')
   GEOM=$(echo "$FOCUSED" | jq -r '.rect | "\(.x),\(.y) \(.width)x\(.height)"')
   APP_ID=$(echo "$FOCUSED" | jq -r '.app_id')
   WHAT="$APP_ID window"
-elif [ "$SUBJECT" = "screen" ] ; then
+elif [ "$SUBJECT" = "screen" ]; then
   GEOM=""
   WHAT="Screen"
-elif [ "$SUBJECT" = "output" ] ; then
+elif [ "$SUBJECT" = "output" ]; then
   GEOM=""
   OUTPUT=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused)' | jq -r '.name')
   WHAT="$OUTPUT"
-elif [ "$SUBJECT" = "window" ] ; then
+elif [ "$SUBJECT" = "window" ]; then
   GEOM=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -r)
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
-   exit 1
+    exit 1
   fi
   WHAT="Window"
-elif [ "$SUBJECT" = "anything" ] ; then
+elif [ "$SUBJECT" = "anything" ]; then
   GEOM=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -o)
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
@@ -175,7 +175,7 @@ if [ "$WAIT" != "no" ]; then
   sleep "$WAIT"
 fi
 
-if [ "$ACTION" = "copy" ] ; then
+if [ "$ACTION" = "copy" ]; then
   takeScreenshot - "$GEOM" "$OUTPUT" | wl-copy --type image/png || die "Clipboard error"
   notifyOk "$WHAT copied to buffer"
 else
